import { describe, it, expect, vi, afterEach } from "vitest";
import { isValidSessionId, parseArguments } from "./cli-args.js";

// Mirror of generateId() in src/sessions/store.ts (not exported there).
// Kept in sync so the validator is tested against the ID shape the app
// actually creates, not a hand-written approximation.
function generateId(): string {
  const ts = new Date().toISOString().replace(/[:.]/g, "").slice(0, 15);
  const hex = Math.random().toString(16).slice(2, 6);
  return `${ts}-${hex}`;
}

describe("isValidSessionId", () => {
  it("accepts real IDs produced by the session store's generateId()", () => {
    for (let i = 0; i < 200; i++) {
      const id = generateId();
      expect(isValidSessionId(id), `generated id should pass: ${id}`).toBe(true);
    }
  });

  it("accepts the real literal format (YYYY-MM-DDThhmm-<4hex>)", () => {
    expect(isValidSessionId("2026-07-30T2358-15a3")).toBe(true);
    expect(isValidSessionId("2026-07-28T1423-ab3f")).toBe(true);
  });

  it("rejects legacy UUIDs (never generated by the app)", () => {
    expect(isValidSessionId("123e4567-e89b-12d3-a456-426614174000")).toBe(false);
    expect(isValidSessionId("12345678-1234-1234-1234-123456789012")).toBe(false);
  });

  it("rejects junk", () => {
    expect(isValidSessionId("")).toBe(false);
    expect(isValidSessionId("not-a-session")).toBe(false);
    expect(isValidSessionId("2026-07-30T2358")).toBe(false); // missing hex suffix
    expect(isValidSessionId("2026-07-30T2358-15a")).toBe(false); // 3 hex chars
    expect(isValidSessionId("2026-07-30T2358-15a33")).toBe(false); // 5 hex chars
    expect(isValidSessionId("2026-07-30T2358-15ag")).toBe(false); // non-hex char
    expect(isValidSessionId("20260730T2358-15a3")).toBe(false); // missing date dashes
    expect(isValidSessionId("2026-07-30T235800-15a3")).toBe(false); // seconds in time (real id has none)
    expect(isValidSessionId("2026-07-30T235-15a3")).toBe(false); // short time
    expect(isValidSessionId(" 2026-07-30T2358-15a3 ")).toBe(false); // surrounding whitespace
    expect(isValidSessionId("2026-07-30T2358-15a3.jsonl")).toBe(false); // filename, not id
  });
});

describe("parseArguments validation", () => {
  afterEach(() => {
    vi.restoreAllMocks();
  });

  // --- --resume ---

  it("accepts a real generated ID passed to --resume", async () => {
    const id = generateId();
    const parsed = await parseArguments(["--resume", id]);
    expect(parsed.resume).toBe(id);
  });

  it("resume without an ID becomes true (session picker)", async () => {
    const parsed = await parseArguments(["--resume"]);
    expect(parsed.resume).toBe(true);
  });

  it("rejects an invalid ID passed to --resume", async () => {
    const stderr = vi.spyOn(process.stderr, "write").mockReturnValue(true);
    const exit = vi.spyOn(process, "exit").mockImplementation(((): never => {
      throw new Error("exit");
    }) as never);
    await parseArguments(["--resume", "not-a-uuid"]).catch(() => {});
    const written = stderr.mock.calls.map((c) => String(c[0])).join("");
    expect(written).toContain('Invalid session ID: "not-a-uuid"');
    expect(written).not.toContain("UUID");
    expect(exit).toHaveBeenCalled();
  });

  // --- positional prompt ---

  it("positional [prompt] is captured as parsed.prompt", async () => {
    const parsed = await parseArguments(["hello world"]);
    expect(parsed.prompt).toBe("hello world");
    expect(parsed.print).toBe(false);
  });

  it("no positional prompt leaves parsed.prompt undefined", async () => {
    const parsed = await parseArguments([]);
    expect(parsed.prompt).toBeUndefined();
  });

  it("--resume with an ID together with a positional prompt is allowed", async () => {
    const id = generateId();
    const parsed = await parseArguments(["--resume", id, "hello"]);
    expect(parsed.resume).toBe(id);
    expect(parsed.prompt).toBe("hello");
  });

  // --- --print / -p ---

  it("--print requires a prompt", async () => {
    const stderr = vi.spyOn(process.stderr, "write").mockReturnValue(true);
    vi.spyOn(process, "exit").mockImplementation(((): never => {
      throw new Error("exit");
    }) as never);
    await parseArguments(["--print"]).catch(() => {});
    const written = stderr.mock.calls.map((c) => String(c[0])).join("");
    expect(written).toContain("--print / -p requires a non-empty prompt.");
  });

  it("--print with a prompt sets print=true and captures prompt", async () => {
    const parsed = await parseArguments(["--print", "explain this"]);
    expect(parsed.print).toBe(true);
    expect(parsed.prompt).toBe("explain this");
  });

  it("short -p flag works", async () => {
    const parsed = await parseArguments(["-p", "summarize"]);
    expect(parsed.print).toBe(true);
    expect(parsed.prompt).toBe("summarize");
  });

  // --- --continue / -c ---

  it("--continue sets continueLast=true", async () => {
    const parsed = await parseArguments(["--continue"]);
    expect(parsed.continueLast).toBe(true);
  });

  it("short -c flag works", async () => {
    const parsed = await parseArguments(["-c"]);
    expect(parsed.continueLast).toBe(true);
  });

  it("--continue together with --resume is rejected", async () => {
    const id = generateId();
    const stderr = vi.spyOn(process.stderr, "write").mockReturnValue(true);
    vi.spyOn(process, "exit").mockImplementation(((): never => {
      throw new Error("exit");
    }) as never);
    await parseArguments(["--continue", "--resume", id]).catch(() => {});
    const written = stderr.mock.calls.map((c) => String(c[0])).join("");
    expect(written).toContain("Cannot use --continue together with --resume.");
  });

  // --- --model / --mode / --debug ---

  it("--model is captured", async () => {
    const parsed = await parseArguments(["--model", "openai/gpt-4.1"]);
    expect(parsed.model).toBe("openai/gpt-4.1");
  });

  it("--mode is captured", async () => {
    const parsed = await parseArguments(["--mode", "architect"]);
    expect(parsed.mode).toBe("architect");
  });

  it("--debug is captured", async () => {
    const parsed = await parseArguments(["--debug"]);
    expect(parsed.debug).toBe(true);
  });

  // --- combined ---

  it("combined flags work together", async () => {
    const parsed = await parseArguments(["-p", "hello", "--model", "openai/gpt-4.1", "--debug"]);
    expect(parsed.print).toBe(true);
    expect(parsed.prompt).toBe("hello");
    expect(parsed.model).toBe("openai/gpt-4.1");
    expect(parsed.debug).toBe(true);
  });
});
